---
title: "Limpieza dataset"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

https://evamaerey.github.io/little_flipbooks_library/data_cleaning/data_cleaning#74 
https://www.gastonsanchez.com/r4strings/cleaning.html

```{r}
pacman::p_load(tidyverse, googlesheets4)
```


```{r}
# raw_dat <- readxl::read_excel(here::here("data", "soja_cba.xlsx"),
#                    .name_repair = janitor::make_clean_names)

raw_dat <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1YL6vwgVu1nyMuZLRZw5uMav7cMt2mDXd7mI2S8Q6Q7c/edit?usp=sharing")%>%  janitor::clean_names()

gs4_auth()
soja <- gs4_get("1YL6vwgVu1nyMuZLRZw5uMav7cMt2mDXd7mI2S8Q6Q7c")
gs4_browse(soja)
raw_dat <- read_sheet(soja, sheet = "raw", range = "A1:AW2708")
raw_dat <- janitor::clean_names(raw_dat)
```

```{r}
glimpse(raw_dat)
```

```{r}
# dat_git <- read_csv("https://raw.githubusercontent.com/juanchiem/soybean/master/data/clean_data.csv")
```

```{r}
dat <- raw_dat %>% 
  select(id_lote, campana, zona, regional, localidad,
         clase_de_suelo,
         cultivo, superficie, 
         rinde = rendimiento_qq_ha,
         antecesor_invernal_18_1, 
         antecesor_estival_17_18, 
         fecha_siembra =fecha_de_siembra_dia_mes, 
         variedad, 
         tecno_herbicidas = biotecnologia_herbicidas,
         tecno_rr = tecnologia_rr, 
         tecno_sts = tecnologia_sts, 
         GM = grupo_de_madurez, semillero, 
         espaciamiento_cm, densidad, 
         riego, napa, agua_inicio=estado_del_perfil_a_la_siembra,  
         adversidad_1, 
         dano_1 = percent_estimados_de_dano, adversidad_2, 
         dano_2 = percent_estimados_de_dano1) %>% 
  # filter(rinde > 10) %>%
  mutate(zona = as.factor(replace_na(zona, '3')), 
         fecha_siembra = lubridate::ymd(fecha_siembra), 
         GM = str_squish(str_to_upper(gsub(',', '\\.', GM))), 
         dano_1 = as.numeric(replace_na(dano_1, '0')), 
         dano_2 = as.numeric(replace_na(dano_2, '0')),
         dano_tot = dano_1 + dano_2,
         cultivo = recode(cultivo,  # cambios manuales
                           'Soja 1°'= 'soja_1',
                           'Soja 2°'= 'soja_2')) %>% 
  mutate(regional = str_trim(string = regional),
         regional = str_to_title(regional), # capital letters
         regional = stringi::stri_trans_general(regional,"Latin-ASCII"), # sacar acentos
         regional = recode(regional,  # cambios manuales
                           'Vicuna Mackenna'= 'V. Mackenna',
                           Montecristo = "Monte Cristo",
                           "Los Surgentes Inriville" = "Los Surgentes-Inriville",
                           "Los Surgentes" = "Los Surgentes-Inriville")) %>% 
   mutate(
    variedad = stringi::stri_trans_general(variedad,"Latin-ASCII"),
    variedad = str_replace_all(variedad, c('STS|IPRO'), ""),
    variedad = str_to_upper(gsub(',', '\\.', variedad)),
    variedad = str_replace_all(variedad, pattern=" ", repl="")) %>% 
  
  mutate(
    tecno_herbicidas = str_to_upper(gsub(',', '\\.', tecno_herbicidas)), 
    tecno_rr = str_to_upper(gsub(',', '\\.', tecno_rr)), 
    tecno_sts = str_to_upper(gsub(',', '\\.', tecno_sts))) %>% 
  mutate(riego = str_to_upper(gsub(',', '\\.', riego))) # %>% 
  
  # mutate(semillero = str_to_upper(gsub(',', '\\.', semillero))) %>% 
  # mutate(id_row = 1:nrow(.))
```

```{r}
glimpse(dat)
```

- Regional

```{r}
# raw_dat %>% 
#   arrange(regional) %>%
#   pull(regional) %>% unique()

dat <- dat %>%
  # mutate(regional = str_trim(string = regional),
  #        regional = str_to_title(regional), # capital letters
  #        regional = stringi::stri_trans_general(regional,"Latin-ASCII"), # sacar acentos
  #        regional = recode(regional,  # cambios manuales
  #                          'Vicuna Mackenna'= 'V. Mackenna',
  #                          Montecristo = "Monte Cristo",
  #                          "Los Surgentes Inriville" = "Los Surgentes-Inriville",
  #                          "Los Surgentes" = "Los Surgentes-Inriville"))
# dat %>% arrange(regional) %>% pull(`regional`) %>% unique()
```

- Localidad

```{r}
dat %>% arrange(localidad) %>% pull(localidad) %>% unique()

dat <- dat %>%
  mutate(localidad = str_to_title(localidad), # capital letters
         localidad = stringi::stri_trans_general(localidad,"Latin-ASCII"))  

dat %>% arrange(localidad) %>% pull(localidad) %>% unique()
```

- Fecha siembra

```{r}
# dat %>% select(campana, fecha_siembra)

# dat <- dat %>% 
#   mutate(season = campana) %>% 
#   separate(campana, c("y_siembra","y_cosecha"), "/") %>%   
#   mutate(y_cosecha = as.numeric(y_cosecha)+2000, 
#          # fecha_siembra = format(fecha_siembra, "%d-%m"),
#          siembra = if_else(fecha_siembra>2018-09-01, fecha ))  
```

- Variedad

```{r}
# https://niderasemillas.com.ar/cultivos/soja
# https://www.donmario.com/catalogo-soja-maiz-trigo/#soja
# https://agriculture.basf.com/ar/es/proteccion-de-cultivos-y-semillas/productos/credenz.html
# https://nksemillas.com.ar/soja

var_aislados <- dat %>%
  group_by(variedad) %>%
  filter(n()==1) %>% ungroup() %>% 
  arrange(variedad) %>% 
  pull(variedad) %>% unique() 
var_aislados

var_name <- dat %>%
  group_by(variedad) %>%
  filter(n()>1) %>% ungroup() %>% 
  arrange(variedad) %>% 
  filter(!variedad %in% c(NA, "OTRO", "OTRA", "VARIAS", "EXPERIMENTAL", "MEZCLA","0")) %>%
  pull(variedad) %>% unique() 
var_name

dat %>% 
  filter(variedad %in% var_name) %>% 
  group_by(variedad) %>%
  filter(n()>1) %>% ungroup() %>%
  pull(variedad) %>% unique() 
```

```{r}
save(raw_dat, dat, var_name, file = here::here("soy_dat.Rdata"))
# write_csv(dat_git, "data/clean_data.csv")
```
