---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = F, message=FALSE, warning=FALSE, 
  comment = "#>"
)
```

Algunas referencias para tener en cuenta: 

[Revista Horizonte digital](https://issuu.com/horizonteadigital/docs/ha_130)

```{r message=FALSE, warning=FALSE, include=FALSE}
pacman::p_load(tidyverse) 
# dat <- read_csv(here::here("data/clean_data.csv"))
load(here::here("soy_dat.Rdata"))

```

## Dataset 

```{r}
glimpse(dat)

```

### Cantidad de datos faltantes por variable:

```{r}
dat %>%
  select(everything()) %>%  # replace to your needs
  summarise_all(funs(sum(is.na(.)))) %>% 
  knitr::kable()
```

## Fecha de siembra x GM

```{r}
pacman::p_load(scales, ggridges)

dat %>% 
  filter(fecha_siembra > '2018-09-15', 
         fecha_siembra < '2018-12-31') %>%
  ggplot(aes(x = fecha_siembra, y = factor(zona))) +
stat_density_ridges(aes(fill = GM), 
                      scale = .95, alpha =0.7, 
                      # quantile_lines = TRUE, quantiles = 2
                      )+
  scale_x_date(date_labels = "%b", breaks = date_breaks("1 months"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+ 
  facet_wrap("campana")+
  labs(x= "Fecha de siembra", y = "Zona agroecológica")
```

## Fecha de siembra x rinde


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dat %>% 
  filter(fecha_siembra > '2018-09-15', 
         fecha_siembra < '2018-12-31') %>%
  filter(!is.na(rinde)) %>% 
  filter(!(cultivo == 'soja_2' & zona ==1 & campana =="2018/19")) %>%
  ggplot(aes(x=lubridate::ymd(fecha_siembra), y=rinde))+
  geom_point(aes(col=campana), alpha =0.5, pch = 21)+
  facet_grid(zona~ cultivo)+
  geom_smooth(aes(col=campana), se = F, 
              span = 1 
              )+
  scale_x_date(date_breaks = "1 month", date_labels =  "%b")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  labs(x = "Fecha de siembra", y = "Rendimiento (qq/ha)")
```

## Variedades

```{r}
dat %>% 
  group_by(variedad) %>%
  tally() %>% 
  arrange(desc(n)) #%>% 
  # knitr::kable()
```

```{r}
dat %>%  
  filter(variedad %in% var_name, 
         dano_tot == 0, 
         rinde > 5, 
         # cultivo == 'soja_1', 
         riego == "NO") %>% 
  count(campana, variedad) %>% 
  arrange(n) %>% 
  filter(n>4) %>% 
  mutate(id = paste0(campana, "-",variedad)) %>% 
  pull(id) %>% unique() ->var_secano
```

### Soja 1° 

```{r fig.height=10}
#http://stulp.gmw.rug.nl/ggplotworkshop/comparinggroupstatistics.html 
dat %>%  
  mutate(id = paste0(campana, "-",variedad)) %>% 
  filter(id %in% var_secano, 
         cultivo == 'soja_1') %>%
  ggplot(aes(x=reorder(factor(variedad), rinde, FUN=median),
             y=rinde))+
  facet_grid(GM ~ campana,  scales="free", switch="y")  +
  coord_flip()+
  stat_summary(fun="mean", geom="point", size=2)+
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", color="blue", width=0.2)
```

### Soja 2°

```{r fig.height=10}
dat %>%  
  mutate(id = paste0(campana, "-",variedad)) %>% 
  filter(id %in% var_secano, 
         cultivo == 'soja_2') %>%
  ggplot(aes(x=reorder(factor(variedad), rinde, FUN=median),
             y=rinde))+
  facet_grid(GM ~ campana,  scales="free", switch="y")  +
  coord_flip()+
  stat_summary(fun="mean", geom="point", size=2)+
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", color="blue", width=0.2)
```
